CREATE TABLE Users(
	UserID CHAR(6),
	FirstName VARCHAR(255) NOT NULL,
	LastName VARCHAR(255),
	School VARCHAR(255),
	AddressUser VARCHAR(255),
	Email VARCHAR(255) NOT NULL,
	PhoneNumber VARCHAR(20) NOT NULL,
	LocationUser VARCHAR(255),
	DateOfBirth DATE,
	Gender VARCHAR(25),
	CONSTRAINT emailValidate CHECK (Email LIKE '%@%'),
	CONSTRAINT genderValidate CHECK (Gender LIKE 'Male' OR Gender LIKE 'Female'),
	CONSTRAINT userIDValidate CHECK (UserID LIKE 'USR[0-9][0-9][0-9]'),
	CONSTRAINT primaryKey PRIMARY KEY (UserID)
)

CREATE TABLE Posts(
	PostID CHAR(6),
	UserID CHAR(6),
	PostDate DATE,
	PostContent VARCHAR(255),
	CONSTRAINT postIdPK PRIMARY KEY (PostID),
	CONSTRAINT userIdFK FOREIGN KEY (UserID) REFERENCES Users(UserID)
		ON UPDATE CASCADE ON DELETE NO ACTION,
	CONSTRAINT usridValidate CHECK (UserID LIKE 'USR[0-9][0-9][0-9]')
)

CREATE TABLE Pages (
	PageID CHAR(6),
	PageName VARCHAR(255),
	PageContent VARCHAR(255),
	CONSTRAINT pageIDPK PRIMARY KEY (PageID)
)

CREATE TABLE PageLikes(
	PageID CHAR(6),
	UserID CHAR(6),
	CONSTRAINT plPK PRIMARY KEY (PageID, UserID),
	CONSTRAINT plFK FOREIGN KEY (PageID) REFERENCES Pages(PageID) 
		ON UPDATE CASCADE ON DELETE NO ACTION,
	CONSTRAINT plFK2 FOREIGN KEY (UserID) REFERENCES Users(UserID)
		ON UPDATE CASCADE ON DELETE NO ACTION
)

CREATE TABLE Friends(
	FriendID CHAR(6),
	UserID CHAR(6),
	CONSTRAINT pkF PRIMARY KEY (FriendID),
	CONSTRAINT fkF FOREIGN KEY (UserID) REFERENCES Users(UserID)
		ON UPDATE CASCADE ON DELETE CASCADE
)

CREATE TABLE PostLikes(
	PostID CHAR(6),
	UserID CHAR(6),
	CONSTRAINT pKey PRIMARY KEY (PostID, UserID),
	CONSTRAINT fKEY FOREIGN KEY (PostID) REFERENCES Users(UserID)
		ON UPDATE CASCADE ON DELETE NO ACTION,
	CONSTRAINT fKEY2 FOREIGN KEY (UserID) REFERENCES Users(UserID)
		ON UPDATE NO ACTION ON DELETE NO ACTION
)

CREATE TABLE Photos(
	PhotoID CHAR(6),
	PostID CHAR(6),
	ImageContent VARCHAR(255),
	CONSTRAINT photoPK PRIMARY KEY (PhotoID),
	CONSTRAINT postFK FOREIGN KEY (PostID) REFERENCES Posts(PostID)
		ON UPDATE CASCADE ON DELETE NO ACTION
)

CREATE TABLE Shares(
	PostID CHAR(6),
	UserID CHAR(6),
	CONSTRAINT sharesPK PRIMARY KEY (PostID, UserID),
	CONSTRAINT sharesFK1 FOREIGN KEY (PostID) REFERENCES Posts(PostID)
		ON UPDATE CASCADE ON DELETE NO ACTION,
	CONSTRAINT sharesFK2 FOREIGN KEY (UserID) REFERENCES Users(UserID)
		ON UPDATE NO ACTION ON DELETE NO ACTION
)

CREATE TABLE Comments(
	CommentID CHAR(6),
	UserID CHAR(6),
	PostID CHAR(6),
	CommentDate DATE,
	CommentContent VARCHAR(255),
	CONSTRAINT pk PRIMARY KEY (CommentID),
	CONSTRAINT fk1 FOREIGN KEY (UserID) REFERENCES Users(UserID)
		ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT fk2 FOREIGN KEY (PostID) REFERENCES Posts(PostID)
		ON UPDATE CASCADE ON DELETE CASCADE,
)

CREATE TABLE CommentLikes(
	CommentID CHAR(6),
	UserID CHAR(6),
	CONSTRAINT pkCL PRIMARY KEY (CommentID, UserID),
	CONSTRAINT fkCL1 FOREIGN KEY (CommentID) REFERENCES Comments(CommentID)
		ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT fkCL2 FOREIGN KEY (UserID) REFERENCES Users(UserID)
		ON UPDATE NO ACTION ON DELETE NO ACTION
)
